version: "3.8"
services:
  foxglove:
    build:
      context: ..
      dockerfile: docker/infrastructure/vis_tools/foxglove.Dockerfile
      cache_from:
        - "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:${TAG}"
        - "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:main"
    image: "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:${TAG}"
    command: ["ros2", "launch", "foxglove_bridge", "foxglove_bridge_launch.xml", "port:=${FOXGLOVE_BRIDGE_PORT:?}"]
    #command: ["ros2", "launch", "foxglove_bridge", "foxglove_bridge_launch.xml", "port:=8765", "send_buffer_limit:=1000", "min_qos_depth:=5", "use_compression:=true"]
    # command: bash -c "ros2 run topic_tools relay /tf /tf_new & ros2 launch rosbridge_server rosbridge_websocket_launch.xml && fg"
    ports:
      - "${FOXGLOVE_BRIDGE_PORT:?}:${FOXGLOVE_BRIDGE_PORT:?}"
